# Font - Gunakan font yang ringan dan pasti ada
font_family      monospace
font_size        10.0

# Performa - Ini yang paling krusial untuk ngilangin delay
sync_to_monitor  no
repaint_delay    2
input_delay      0
sleep_detection_number 0

# Shell Integration - Kadang ini yang bikin berat di awal
shell_integration disabled

# peringatan saat close
confirm_os_window_close 0

#background transparan
#background_opacity 0.65
